export const ADD_CAR = 'ADD_CAR';
export const ADD_CARS = 'ADD_CARS';
export const ADD_CARS_ERROR = 'ADD_CARS_ERROR';
export const TOGGLE_ITEM_CART = 'TOGGLE_ITEM_CART';
export const START_LOADING_CARS = 'START_LOADING_CARS';
export const START_AUTO_COMPLETE = 'START_AUTO_COMPLETE';
export const SUCCESS_AUTO_COMPLETE = 'SUCCESS_AUTO_COMPLETE';
